### ISSUE TITLE
ipfs load go-ds-s3 error

### ISSUE THREAD

**Issue by mapdog-mapdog** [ipfs/go-ds-s3#176]
I have git clone latest "go-ipfs" and latest "go-ds-s3" release，and make build & make install ,but when i "ipfs init",come out error:

" Error: error loading plugins: loading plugin /root/.ipfs/plugins/go-ds-s3.so: plugin.Open("/root/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package internal/unsafeheader"

I don't understand about this error,the “ReadMe” of "go-ds-s3" say:
git clone https://github.com/ipfs/go-ipfs
> cd go-ipfs

# Pull in the datastore plugin (you can specify a version other than latest if you'd like).
> go get github.com/ipfs/go-ds-s3@latest

# Add the plugin to the preload list.
> echo "s3ds github.com/ipfs/go-ds-s3/plugin 0" >> plugin/loader/preload_list

# Rebuild go-ipfs with the plugin
> make build

# (Optionally) install go-ipfs
> make install

 I just do like that,why have error?????

**Comment by aschmahmann** [comment]
The approach you described is for building an in-tree plugin. However the error is from an out of tree plugin since /root/.ipfs/plugins/go-ds-s3.so: shouldn't exist.

Perhaps you tried with an out of tree plugin first. Try deleting that plugin shared object file and trying again with the in-tree plugin.

**Comment by BigLep** [comment]
Closing for now due to inactivity.  Feel free to reopen if this is still an issue.
