### ISSUE TITLE
Missing method for ipfs v0.6.0

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ds-s3#97]
Building against go-ipfs v0.6.0 errors with:

./s3.go:375:5: cannot use (*S3Bucket)(nil) (type *S3Bucket) as type datastore.Batching in assignment:
	*S3Bucket does not implement datastore.Batching (missing Sync method)

**Comment by aschmahmann** [comment]
@ianopolous I'm pretty sure you're building using the wrong version of this repo. That function has been here https://github.com/ipfs/go-ds-s3/blob/06797d06b9e67ef78d85a8107246fab788212ef6/s3.go#L101 since go-ipfs v0.5.0. Also, I just just replacing the go-ipfs v0.5.0 dependency with v0.6.0 and it builds just fine.

Any guidance on how to reproduce what you're doing?

**Comment by ianopolous** [comment]
Sorry, my bad, my remote was still pointing at MichaelMure's since he fixed the last release. You are right, the latest works fine.
